version: '3.3'

services:
  codecamp__freeboard:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 4000:4000
    volumes:
      - ./src:/codecamp__freeboard/src
